Scatter plots
swhustla/comparison_of_time_series_methods pull request #156
Opened 2023-03-12 22:02 UTC by karukes

2023-03-14 11:52 UTC, swhustla commented on main_plot.py
@karukes does this file need a bit of tidying up? It looks like you have disabled a bunch of plot types. Or am I mistaken?

2023-03-14 11:53 UTC, swhustla commented on methods/plot_correlation_Npoints.py
File naming should conform to PEP8 standards (check with chatGPT)

2023-03-14 11:53 UTC, swhustla commented on methods/plot_results_in_box_plot.py
>              print(f"Saving {dataset_name} {chosen_metric} boxplot plot")
Isn't there a duplication of writing to plot_params here?

2023-03-14 11:54 UTC, swhustla commented on methods/plot_results_in_box_plot.py
> +            ),
Can you add comments to explain what is going on here? Why plotting twice to boxplot?

2023-03-14 11:55 UTC, swhustla commented on plots/plot_correlation_Npoints.py
File naming needs to be PEP8 standard - see earlier comment

2023-03-14 11:56 UTC, swhustla commented on plots/plot_correlation_Npoints.py
> +        # create more ticks on the x axis
Maybe get ChatGPT to help you restructure some of this, it seems slightly repetitive code.

2023-03-14 11:58 UTC, swhustla requested changes
Hi @karukes a few comments and feedback for you :)

2023-03-14 22:08 UTC, karukes commented on main_plot.py
@swhustla it is disabled in order not to make all the plots at once (without need). Agree, maybe this part could be organised bette.

2023-03-29 09:10 UTC, swhustla approved these changes
Looks good, thanks for the quick changes

2023-03-29 13:46 UTC, merged